version: "3"

services:
  app:
    build:
      context: .
      args:
        ENVIRONMENT: local
    ports:
      - "8080:8080"
    entrypoint: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    volumes:
      - ./app:/usr/src/app
      - ./models:/usr/src/models
    environment:
      - db_host=postgresql://postgres:postgres@postgresdb:5432/postgres
    depends_on:
      - postgresdb

  app-test:
    build:
      context: .
      args:
        ENVIRONMENT: test
    volumes:
      - .:/usr/src
    entrypoint: ["sleep", "infinity "]
    environment:
      - db_host=postgresql://postgres:postgres@postgrestest:5432/postgres
      - SQLALCHEMY_SILENCE_UBER_WARNING=1
      - app_env=test
    depends_on:
      - postgrestest

  postgresdb:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env-local
    volumes:
      - ./data:/var/lib/postgresql/data

  postgrestest:
    image: postgres:14.1-alpine
    env_file:
      - .env-local

volumes:
  pgdb:



